### ISSUE TITLE
Implemented Planners

### ISSUE THREAD

**Issue by arndz** [mh0797/interPlan#5]
Hi Marcel,

Thanks for this amazing work!

I've seen that you have evaluated DTPP and GameFormer on the interPlan benchmark but I couldn't find the models in your repo - how did you evaluate them?

Thanks in advance!

Best,
Aron

**Comment by mh0797** [comment]
Hi @arndz,
Thanks!

We used the official nuPlan implementations of both models as well as the published checkpoints.
Unfortunately, due to license issues, we couldn't redistribute the code publicly.
Feel free to send me a private email if you want to know the details (marcel.hallgarten@uni-tuebingen.de).

Best
Marcel
