### ISSUE TITLE
potential bugs and improvements in v1.1. Encounter OOM when running sumulation.

### ISSUE THREAD

**Issue by richie-live** [mh0797/interPlan#8]
https://github.com/motional/nuplan-devkit/issues/237#issue-1616067992

The Interplan is designed for nuplan v1.1, but nuplan v1.1 have this problem, do you known how to solve this problem? thanks

**Comment by mh0797** [comment]
Hi @richie-live 

interPlan indeed uses nuplan-v1.1 and it probably won't run with v1.0.

Re. your issues:
you should be able to reduce the memory footprint by loading all model components in the `initialize` method rather than the `init` method of your planner class, as the former is only called upon the start of the simulation runner instance. Also, you might want to test different workers such as `single_machine_thread_pool` or `sequential`. In general I think however, that to work effectively with nuPlan, more than 4 cores are recommendable.
